# Generated by Django 5.2.1 on 2025-06-04 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=15)),
                ('Age', models.IntegerField()),
                ('Email', models.EmailField(max_length=20)),
            ],
            options={
                'db_table': 'Student',
            },
        ),
    ]
