# Generated by Django 5.2.1 on 2025-06-10 03:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_department_hod'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='hod',
            name='department',
        ),
        migrations.AlterModelTable(
            name='department',
            table='Dep',
        ),
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('department_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Faculties', to='myapp.department')),
                ('subjects', models.ManyToManyField(related_name='faculties', to='myapp.subject')),
            ],
        ),
    ]
