# Generated by Django 5.2.1 on 2025-06-10 03:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_subject_remove_hod_department_alter_department_table_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='hod',
            table='Hod',
        ),
    ]
