# Generated by Django 5.2.1 on 2025-06-10 03:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_alter_hod_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='faculty',
            table='faculty',
        ),
        migrations.AlterModelTable(
            name='subject',
            table='Sub',
        ),
    ]
