# Generated by Django 5.2.1 on 2025-06-10 03:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_alter_faculty_table_alter_subject_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='faculty',
            table='Faculty',
        ),
    ]
