# Generated by Django 5.2.1 on 2025-06-11 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_alter_faculty_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15)),
                ('age', models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='faculty',
            name='subjects',
            field=models.ManyToManyField(related_name='Faculties', to='myapp.subject'),
        ),
    ]
