# Generated by Django 5.2.1 on 2025-06-14 14:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_state_dist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dist',
            name='dist_name',
        ),
        migrations.RemoveField(
            model_name='dist',
            name='state',
        ),
        migrations.RemoveField(
            model_name='state',
            name='state_name',
        ),
    ]
